// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import ResumeSvg from "./assets/resume.svg";
import LinkedinSvg from "./assets/linkedin.svg";
import CurriculoPdf from "./assets/curriculo.pdf";
import GithubMarkPng from "./assets/github-mark.png";

import './Portfolio.css'
;

var github = GithubMarkPng;

var resume = ResumeSvg;

var linkedin = LinkedinSvg;

var cv = CurriculoPdf;

function Portfolio(props) {
  return JsxRuntime.jsx("main", {
              children: JsxRuntime.jsx("div", {
                    children: JsxRuntime.jsxs("div", {
                          children: [
                            JsxRuntime.jsx("p", {
                                  children: "OI 👏 EU SOU O SILAS",
                                  id: "apresentation"
                                }),
                            JsxRuntime.jsxs("div", {
                                  children: [
                                    JsxRuntime.jsx("p", {
                                          children: "BACK"
                                        }),
                                    JsxRuntime.jsxs("div", {
                                          children: [
                                            JsxRuntime.jsx("a", {
                                                  children: JsxRuntime.jsx("img", {
                                                        src: github
                                                      }),
                                                  id: "github",
                                                  href: "https://github.com/silasms",
                                                  target: "_blank"
                                                }),
                                            JsxRuntime.jsx("a", {
                                                  children: JsxRuntime.jsx("img", {
                                                        src: linkedin
                                                      }),
                                                  href: "https://www.linkedin.com/in/silas-medeiros/"
                                                }),
                                            JsxRuntime.jsx("a", {
                                                  children: JsxRuntime.jsx("img", {
                                                        src: resume
                                                      }),
                                                  href: cv,
                                                  target: "_blank"
                                                })
                                          ]
                                        })
                                  ],
                                  id: "informations"
                                }),
                            JsxRuntime.jsx("p", {
                                  children: "DEVELOPER"
                                }),
                            JsxRuntime.jsx("p", {
                                  children: "Tenho 23 anos, sou desenvolvedor backend com 3 anos de experiencia trabalhando no mercado profissional.",
                                  id: "exp"
                                })
                          ],
                          id: "profession"
                        }),
                    id: "main",
                    style: {
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "center"
                    }
                  })
            });
}

var make = Portfolio;

export {
  github ,
  resume ,
  linkedin ,
  cv ,
  make ,
}
/*  Not a pure module */
